server:
  port: 8082
  servlet:
    context-path: /abc
jdbc:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://39.108.71.225:3306/test?characterEncoding=utf-8&useSSL=false
  username: root
  password: root

mybatis_config_file: mybatis-config.xml
mapper_path: /mapper/**.xml
entity_package: com.example.abc.entity